version: "3.8"

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: market
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local
    